name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [runs-on=${{ github.run_id }}/runner=buf-16cpu-linux-x64/disk=large, macos-latest]
    name: Unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: runs-on/action@cd2b598b0515d39d78c38a02d529db87d2196d1e # v2.0.3
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-build-cache
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Make
        run: choco install make
        if: runner.os == 'Windows'
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Execute tests
        run: make test
