name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: macos-15
          - os: windows-2025
          - os: ubuntu-24.04
            bazel: 9.x
    name: Unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          disk-cache: true
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Install Make
        run: choco install make
        if: runner.os == 'Windows'
      - name: Install go
        uses: actions/setup-go@v7
        with:
          go-version: stable
          cache: true
      - name: Execute tests
        run: make test
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
  test-workspace:
    name: Unit tests (WORKSPACE mode)
    runs-on: ubuntu-24.04
    steps:
      - uses: bazel-contrib/setup-bazel@0.19.0
        with:
          disk-cache: true
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Execute tests
        run: bazel test --enable_workspace --noenable_bzlmod --test_output=errors //...
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Install go
        uses: actions/setup-go@v7
        with:
          go-version: stable
          cache: true
      - name: Check generated files
        run: make checkgenerate
