name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  conformance:
    name: Conformance testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: go.work.sum
      - name: Test conformance
        run: make conformance
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: go.work.sum
      - name: Execute tests
        run: make tests