name: CI
on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 22 * * *'
  workflow_dispatch: {} # support manual runs
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-build-cache
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Make
        run: choco install make
        if: runner.os == 'Windows'
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      - name: Execute tests
        run: make test
