name: Publish to BCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. "v1.0.0")'
        required: true
      templates_ref:
        description: 'Git ref to read .bcr templates from instead of the tag (e.g. "main")'
        required: false

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.5.0
    with:
      draft: false
      tag_name: ${{ inputs.tag_name || github.ref_name }}
      templates_ref: ${{ inputs.templates_ref }}
      registry_fork: bufbuild/bazel-central-registry
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
