name: Publish to BCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. "v1.0.0")'
        required: true

permissions:
  contents: write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v0.2.1
    with:
      tag_name: ${{ github.ref_name }}
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
