name: Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release (e.g. "v1.0.0")'
        required: true

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  create-release-tag:
    name: Create release tag
    runs-on: runs-on=${{ github.run_id }}/runner=buf-1cpu-linux-x64
    steps:
      - uses: runs-on/action@cd2b598b0515d39d78c38a02d529db87d2196d1e # v2.0.3
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = '${{ github.event.inputs.tag_name }}';
            const commitTag = await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag,
              message: tag,
              object: context.sha,
              type: 'commit',
            });
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: commitTag.data.sha,
            });
  release:
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.2.3
    needs: create-release-tag
    with:
      release_files: protovalidate-cc-*.tar.gz
      prerelease: false
      draft: true
      tag_name: ${{ github.event.inputs.tag_name }}
